name: Main

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'
    
permissions:
  contents: write
  
jobs:
  check-dist:
    name: Check dist for incompatible changes
    uses: ./.github/workflows/check-dist.yml
    with:
      dist_path: "dist"

  tag-and-release:
    runs-on: ubuntu-latest
    name: Tag and Release
    needs: check-dist
    if: ${{ needs.check-dist.outputs.can_publish == 'true' }}
    steps:
      - name: Check for changes
        id: changes
        run: |
          echo "can_publish=${{ needs.check-dist.outputs.can_publish }}" >> $GITHUB_OUTPUT
          echo "has_incompatible_changes=${{ needs.check-dist.outputs.has_incompatible_changes }}" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Create Tag
        uses: oobook/autonomous-tag@v1
        id: tag-generation
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: oobook/autonomous-release@v1
        id: release-generation
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          tag: "${{ steps.tag-generation.outputs.tag }}"
          prerelease: true

